# Use this Dockerfile if you build locally: npm run build first
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/* /var/cache/apk/* /tmp/*
COPY dist /usr/share/nginx/html
RUN echo 'server { listen 80; root /usr/share/nginx/html; index index.html; location / { try_files $uri /index.html; } }' > /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

